log4j.rootLogger=DEBUG, LOG1

log4j.appender.LOG1=org.apache.log4j.FileAppender

log=./logs/App/log4j
log4j.appender.LOG1.File=${log}/log.out

log4j.appender.LOG1.layout=org.apache.log4j.PatternLayout
log4j.appender.LOG1.layout.conversionPattern=%d %p [%t] %C - %m%n